//
// Created by kolos on 7/27/20.
//

#ifndef RC_BEAGLEBONE_FLIGHT_CONTROLLER_SERVOCONTROLLER_H
#define RC_BEAGLEBONE_FLIGHT_CONTROLLER_SERVOCONTROLLER_H


class ServoController {

};


#endif //RC_BEAGLEBONE_FLIGHT_CONTROLLER_SERVOCONTROLLER_H
